[CmdletBinding()]
param()

# Plan 06 P5: the V3 package builds its trusted guard projects from its own build/ baseline.
# The package is copied to a temporary directory outside any host repository, surrounded by hostile host files
# (Directory.Build.props/targets, Directory.Packages.props, NuGet.config and global.json), and must still validate,
# generate, check and test with locked restore and a clean import allowlist, without writing bin/obj into the package.

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$package = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$temp = [IO.Path]::GetFullPath((Join-Path ([IO.Path]::GetTempPath()) "v3-build-isolation-$([Guid]::NewGuid().ToString('N'))"))
$copy = Join-Path $temp 'docs/guards/V3'
$profile = Join-Path $temp 'profile'
$generationRoot = [IO.Path]::GetFullPath("$temp-generation")
$output = Join-Path $generationRoot 'v3/gates/stage'
$locks = Join-Path $temp 'locks'
$utf8 = [Text.UTF8Encoding]::new($false)

function Write-Text([string] $path, [string] $content) {
    [void][IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($path))
    [IO.File]::WriteAllText($path, $content, $utf8)
}

function Invoke-Runner([int] $expected, [string[]] $arguments, [string] $label, [string] $expectText) {
    $result = @(& pwsh -NoProfile -File (Join-Path $copy 'commands/Invoke-V3.ps1') -ProfileDirectory $profile -TargetRoot $temp -GenerationRoot $generationRoot -OutputDirectory $output @arguments 2>&1) -join ' | '
    if ($LASTEXITCODE -ne $expected) { throw "$label expected exit $expected, got ${LASTEXITCODE}: $result" }
    # Error records wrap at the host width; compare without whitespace and line separators.
    $flat = ($result -replace '[\s|]', ''); $wanted = ($expectText -replace '\s', '')
    if ($expectText -and -not $flat.Contains($wanted, [StringComparison]::OrdinalIgnoreCase)) { throw "$label did not report '$expectText': $result" }
    Write-Host "PASS $label"
}

function Assert-Throws([scriptblock] $action, [string] $label, [string] $expectText) {
    try { & $action } catch {
        if (-not $_.Exception.Message.Contains($expectText, [StringComparison]::OrdinalIgnoreCase)) { throw "$label failed for an unexpected reason: $($_.Exception.Message)" }
        Write-Host "PASS $label"
        return
    }
    throw "$label did not fail."
}

try {
    foreach ($file in Get-ChildItem -LiteralPath $package -Recurse -File) {
        $relative = [IO.Path]::GetRelativePath($package, $file.FullName).Replace('\', '/')
        if ($relative -match '(^|/)(bin|obj)/') { continue }
        $destination = Join-Path $copy $relative
        [void][IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($destination))
        [IO.File]::Copy($file.FullName, $destination)
    }

    # Hostile host configuration surrounding the package; none of it may take effect.
    Write-Text (Join-Path $temp 'Directory.Build.props') '<Project><PropertyGroup><NuGetAudit>false</NuGetAudit><ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally></PropertyGroup><Target Name="HostileHostProps" BeforeTargets="Build"><Error Text="host Directory.Build.props was imported" /></Target></Project>'
    Write-Text (Join-Path $temp 'Directory.Build.targets') '<Project><Target Name="HostileHostTargets" BeforeTargets="Build"><Error Text="host Directory.Build.targets was imported" /></Target></Project>'
    Write-Text (Join-Path $temp 'Directory.Packages.props') '<Project><PropertyGroup><ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally></PropertyGroup></Project>'
    Write-Text (Join-Path $temp 'NuGet.config') '<configuration><packageSources><clear /><add key="hostile" value="https://hostile.invalid/v3/index.json" /></packageSources></configuration>'
    Write-Text (Join-Path $temp 'global.json') '{ "sdk": { "version": "9.9.999", "rollForward": "disable" } }'

    Copy-Item -LiteralPath (Join-Path $package 'examples/minimal') -Destination $profile -Recurse
    [void][IO.Directory]::CreateDirectory($generationRoot)
    Write-Text (Join-Path $temp 'src/App/App.csproj') '<Project><ItemGroup><ProjectReference Include="../Core/Core.csproj" /></ItemGroup></Project>'

    Invoke-Runner 0 @('-Mode', 'Validate') 'isolated package validates'
    Invoke-Runner 0 @('-Mode', 'Generate') 'isolated package generates the Stage Gate'
    Invoke-Runner 0 @('-Mode', 'Check') 'isolated package checks generated bytes'
    Invoke-Runner 1 @('-Mode', 'Test', '-LockMode', 'Locked', '-LockRoot', $locks) 'locked restore without a lock file fails' 'lock file is missing'
    Invoke-Runner 0 @('-Mode', 'Test', '-LockMode', 'Update', '-LockRoot', $locks) 'update restore writes the lock file'
    Invoke-Runner 0 @('-Mode', 'Test', '-LockMode', 'Locked', '-LockRoot', $locks) 'locked restore with the reviewed lock passes'

    $lockFile = Join-Path $locks 'Sample.Guards.StageGate.Tests.packages.lock.json'
    $reviewed = [IO.File]::ReadAllText($lockFile)
    $lock = $reviewed | ConvertFrom-Json -AsHashtable -Depth 20
    $framework = @($lock.dependencies.Keys)[0]
    $lock.dependencies[$framework]['xunit'].contentHash = 'AAAA' + $lock.dependencies[$framework]['xunit'].contentHash.Substring(4)
    [IO.File]::WriteAllText($lockFile, ($lock | ConvertTo-Json -Depth 20), $utf8)
    Invoke-Runner 1 @('-Mode', 'Test', '-LockMode', 'Locked', '-LockRoot', $locks) 'tampered content hash fails' 'changed during locked restore'
    $lock = $reviewed | ConvertFrom-Json -AsHashtable -Depth 20
    $transitive = @($lock.dependencies[$framework].Keys | Where-Object { $lock.dependencies[$framework][$_].type -eq 'Transitive' })[0]
    $lock.dependencies[$framework].Remove($transitive)
    [IO.File]::WriteAllText($lockFile, ($lock | ConvertTo-Json -Depth 20), $utf8)
    Invoke-Runner 1 @('-Mode', 'Test', '-LockMode', 'Locked', '-LockRoot', $locks) 'lock missing a restored package fails' 'changed during locked restore'
    [IO.File]::WriteAllText($lockFile, $reviewed, $utf8)

    $reports = Join-Path $temp 'artifacts/guards/v3/build/stage-gate'
    foreach ($name in @('Sample.Guards.StageGate.Tests.imports.pre-build.json', 'Sample.Guards.StageGate.Tests.imports.post-build.json')) {
        $report = Get-Content -LiteralPath (Join-Path $reports $name) -Raw | ConvertFrom-Json
        if ($report.status -ne 'pass' -or $report.categories.baseline -lt 1) { throw "Import allowlist evidence is missing or failing: $name" }
    }
    Write-Host 'PASS import allowlist evidence recorded'

    # A project that imports an arbitrary file must be rejected by the pre-build allowlist.
    Import-Module (Join-Path $copy 'build/GuardBuild.psm1') -Force
    $caseRoot = Join-Path $temp 'import-case'
    Write-Text (Join-Path $temp 'hostile.props') '<Project><PropertyGroup><NuGetAudit>false</NuGetAudit></PropertyGroup></Project>'
    $caseProject = Join-Path $caseRoot 'ImportCase.csproj'
    Write-Text $caseProject '<Project Sdk="Microsoft.NET.Sdk"><Import Project="../hostile.props" /><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>'
    $context = New-GuardBuildContext -ArtifactsRoot (Join-Path $temp 'artifacts/build/import-case') -LockRoot $locks -ReportRoot (Join-Path $temp 'artifacts/guards/import-case') -LockMode Update
    Assert-Throws { Invoke-GuardRestore $context $caseProject @($caseProject) } 'undeclared project import fails' 'NuGet audit is weaker'
    Write-Text $caseProject '<Project Sdk="Microsoft.NET.Sdk"><Import Project="../hostile-empty.props" /><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>'
    Write-Text (Join-Path $temp 'hostile-empty.props') '<Project />'
    Assert-Throws { Invoke-GuardRestore $context $caseProject @($caseProject) } 'undeclared import outside the allowlist fails' 'outside the allowlist'

    Assert-GuardNoSourceTreeOutput $copy
    Write-Host 'PASS no bin/obj inside the package source tree'
    Write-Host 'V3 build baseline isolation tests passed.'
}
finally {
    Remove-Module GuardBuild -ErrorAction SilentlyContinue
    if ([IO.Directory]::Exists($temp)) { [IO.Directory]::Delete($temp, $true) }
    if ([IO.Directory]::Exists($generationRoot)) { [IO.Directory]::Delete($generationRoot, $true) }
}
