[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$package = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$repo = [IO.Path]::GetFullPath((Join-Path $package '../../..'))
$fixtureParent = [IO.Path]::GetFullPath((Join-Path $repo 'artifacts/guards'))
$fixture = [IO.Path]::GetFullPath((Join-Path $fixtureParent "v3-fixture-$([Guid]::NewGuid().ToString('N'))"))
$profile = Join-Path $fixture 'profile'
$runner = Join-Path $package 'scripts/Invoke-V3.ps1'
$output = 'docs/guards/V3/generated/dotnet'
if (-not $fixture.StartsWith($fixtureParent + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) { throw 'Unsafe fixture path.' }

function Assert-Run {
    param([int] $Expected, [string[]] $Arguments, [string] $Label)
    $result = @(& pwsh -NoProfile -File $runner -ProfileDirectory $profile -TargetRoot $fixture -OutputDirectory $output @Arguments 2>&1)
    if ($LASTEXITCODE -ne $Expected) { throw "$Label expected exit $Expected, got ${LASTEXITCODE}: $($result -join ' | ')" }
}

$passed = $false
try {
    [void] [IO.Directory]::CreateDirectory((Join-Path $fixture 'src/App'))
    [void] [IO.Directory]::CreateDirectory((Join-Path $fixture 'docs/plans'))
    Copy-Item -LiteralPath (Join-Path $package 'examples/minimal') -Destination $profile -Recurse
    [IO.File]::WriteAllText((Join-Path $fixture '.gitignore'), "docs/guards/V3/generated/`nartifacts/`n")
    [IO.File]::WriteAllText((Join-Path $fixture 'NuGet.Offline.Config'), '<configuration><packageSources><clear /></packageSources></configuration>')
    $projectFile = Join-Path $fixture 'src/App/App.csproj'
    $good = '<Project><ItemGroup><ProjectReference Include="../Core/Core.csproj" /></ItemGroup></Project>'
    $bad = '<Project><ItemGroup><ProjectReference Include="../Legacy/Legacy.csproj" /></ItemGroup></Project>'
    [IO.File]::WriteAllText($projectFile, $good)
    Assert-Run 0 @('-Mode', 'Validate') 'validate synthetic profile'
    $sampleRule = Join-Path $profile 'rules/ARCH.SAMPLE.json'
    $originalRule = [IO.File]::ReadAllText($sampleRule)
    [IO.File]::WriteAllText($sampleRule, $originalRule.Replace('forbidden-project-reference', 'unsupported-detector'))
    Assert-Run 1 @('-Mode', 'Validate') 'unsupported detector fails validation'
    [IO.File]::WriteAllText($sampleRule, $originalRule)
    [IO.File]::WriteAllText((Join-Path $profile 'rules/ARCH.UNCOVERED.json'), '{"formatVersion":1,"id":"ARCH.UNCOVERED","title":"Future semantic detector","kind":"none","enforcement":"advisory","coverage":"none","authority":"Synthetic example"}')
    Assert-Run 0 @('-Mode', 'Validate') 'advisory uncovered rule remains explicit'
    Assert-Run 0 @('-Mode', 'Generate') 'generate .NET project'
    Assert-Run 0 @('-Mode', 'Check') 'generated project check'
    $generatedProject = Join-Path $fixture "$output/GuardV3.Tests.csproj"
    [IO.File]::AppendAllText($generatedProject, "`n")
    Assert-Run 1 @('-Mode', 'Check') 'generated byte drift'
    Assert-Run 0 @('-Mode', 'Generate') 'regenerate after drift'
    Remove-Item -LiteralPath (Join-Path $profile 'rules/ARCH.UNCOVERED.json') -Force
    Assert-Run 1 @('-Mode', 'Check') 'removed rule leaves stale snapshot'
    Assert-Run 0 @('-Mode', 'Generate') 'regenerate removes stale rule snapshot'
    Assert-Run 0 @('-Mode', 'Test', '-NuGetConfig', 'NuGet.Offline.Config') 'allowed project reference and detector fixtures'
    $ruleData = Get-Content -LiteralPath $sampleRule -Raw | ConvertFrom-Json -AsHashtable
    $ruleData.sourcePattern = 'src/Never/**/*.csproj'
    [IO.File]::WriteAllText($sampleRule,($ruleData | ConvertTo-Json -Depth 20))
    Assert-Run 0 @('-Mode', 'Generate') 'generate unmatched-source rule'
    Assert-Run 1 @('-Mode', 'Test', '-NuGetConfig', 'NuGet.Offline.Config') 'unmatched-source rule cannot pass'
    $ruleData.sourcePattern = 'src/**/*.csproj'
    $ruleData.negativeFixture.referenceInclude = '../Core/Core.csproj'
    [IO.File]::WriteAllText($sampleRule,($ruleData | ConvertTo-Json -Depth 20))
    Assert-Run 0 @('-Mode', 'Generate') 'generate ineffective negative fixture'
    Assert-Run 1 @('-Mode', 'Test', '-NuGetConfig', 'NuGet.Offline.Config') 'ineffective negative fixture cannot pass'
    [IO.File]::WriteAllText($sampleRule, $originalRule)
    Assert-Run 0 @('-Mode', 'Generate') 'restore effective rule'
    [IO.File]::WriteAllText($projectFile, $bad)
    Assert-Run 1 @('-Mode', 'Test', '-NuGetConfig', 'NuGet.Offline.Config') 'forbidden project reference'
    [IO.File]::WriteAllText($projectFile, $good)

    $plan = 'docs/plans/20260914-sample.plan.json'
    $planFile = Join-Path $fixture $plan
    [IO.File]::WriteAllText($planFile, '{"formatVersion":1,"id":"20260914-sample","title":"Sample dependency","plannedPaths":["src/App/App.csproj"],"ruleIds":["ARCH.SAMPLE"],"validationCommands":["dotnet test"],"decisionPaths":[]}')
    [IO.File]::WriteAllText((Join-Path $fixture 'docs/plans/20260914-sample.md'), '# Sample dependency')
    Assert-Run 1 @('-Mode', 'Pre', '-PlanPath', $plan) 'risk without decision'
    $decision = 'docs/plans/20260914-decision.json'
    [IO.File]::WriteAllText((Join-Path $fixture $decision), '{"formatVersion":1,"id":"sample-decision","owner":"sample","summary":"Sample dependency","affectedPaths":["src/App/App.csproj"],"rationale":"Synthetic test"}')
    [IO.File]::WriteAllText($planFile, '{"formatVersion":1,"id":"20260914-sample","title":"Sample dependency","plannedPaths":["src/App/App.csproj"],"ruleIds":["ARCH.SAMPLE"],"validationCommands":["dotnet test"],"decisionPaths":["docs/plans/20260914-decision.json"]}')
    Assert-Run 0 @('-Mode', 'Pre', '-PlanPath', $plan) 'risk with decision'

    Push-Location $fixture
    try {
        & git init -q
        & git config user.email guard-v3@example.invalid
        & git config user.name 'Guard V3 Fixture'
        & git config core.autocrlf false
        & git add .
        & git commit -qm baseline
        if ($LASTEXITCODE -ne 0) { throw 'Fixture commit failed.' }
    }
    finally { Pop-Location }
    [IO.File]::AppendAllText($projectFile, "`n<!-- planned -->")
    Assert-Run 0 @('-Mode', 'Diff', '-PlanPath', $plan, '-BaseRef', 'HEAD', '-NuGetConfig', 'NuGet.Offline.Config') 'planned diff'
    [IO.File]::WriteAllText((Join-Path $fixture 'src/Unplanned.cs'), 'class Unplanned {}')
    Assert-Run 1 @('-Mode', 'Diff', '-PlanPath', $plan, '-BaseRef', 'HEAD', '-NuGetConfig', 'NuGet.Offline.Config') 'out-of-plan diff'
    $passed = $true
    Write-Host 'V3 synthetic positive/negative tests passed.'
}
finally {
    if ($passed -and [IO.Directory]::Exists($fixture)) {
        $verified = [IO.Path]::GetFullPath($fixture)
        if (-not $verified.StartsWith($fixtureParent + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) { throw 'Unsafe fixture cleanup path.' }
        Remove-Item -LiteralPath $verified -Recurse -Force
    }
    elseif (-not $passed) { Write-Warning "Failed fixture retained at $fixture" }
}
