<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" VersionOverride="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" VersionOverride="17.8.0" />
    <PackageReference Include="Moq" />
    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="System.Text.RegularExpressions" />
    <PackageReference Include="xunit" VersionOverride="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" VersionOverride="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Platform\Notifications\IFX.Platform.Notifications.Infrastructure.SendGrid\IFX.Platform.Notifications.Infrastructure.SendGrid.csproj" />
    <ProjectReference Include="..\..\src\Platform\Notifications\IFX.Platform.Notifications.Contracts\IFX.Platform.Notifications.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Platform\Notifications\IFX.Platform.Notifications.Composition\IFX.Platform.Notifications.Composition.csproj" />
  </ItemGroup>

</Project>
