<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IFX.Platform.Authentication.Runtime\IFX.Platform.Authentication.Runtime.csproj" />
    <ProjectReference Include="..\IFX.Platform.Authentication.Infrastructure.Cognito\IFX.Platform.Authentication.Infrastructure.Cognito.csproj" />
    <ProjectReference Include="..\IFX.Platform.Authentication.Infrastructure.Auth0\IFX.Platform.Authentication.Infrastructure.Auth0.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
