[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$packageRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'));$repoRoot=[IO.Path]::GetFullPath((Join-Path $packageRoot '../../..'));$runRoot=Join-Path $repoRoot 'artifacts/guards/v4/p8-acceptance';$buildRoot=Join-Path $packageRoot 'build';$project=Join-Path $packageRoot 'core/host/V4.Guards.Host/V4.Guards.Host.csproj';$dll=Join-Path $runRoot 'build/bin/V4.Guards.Host/release/v4-guards.dll';$failures=[Collections.Generic.List[string]]::new()
function Write-Utf8([string]$Path,[string]$Text){[void][IO.Directory]::CreateDirectory((Split-Path -Parent $Path));[IO.File]::WriteAllText($Path,$Text,[Text.UTF8Encoding]::new($false))}
function Tree-Hash([string]$Root){$lines=@(Get-ChildItem $Root -File -Recurse -Force|Sort-Object FullName|ForEach-Object{"$([IO.Path]::GetRelativePath($Root,$_.FullName).Replace('\','/')):$((Get-FileHash $_.FullName).Hash.ToLowerInvariant())"});[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes(($lines-join"`n")))).ToLowerInvariant()}
function Host([string[]]$Arguments){$output=@(& dotnet $dll @Arguments 2>&1);[pscustomobject]@{Code=$LASTEXITCODE;Text=($output-join"`n")}}
if(Test-Path $runRoot){Remove-Item -LiteralPath $runRoot -Recurse -Force};[void][IO.Directory]::CreateDirectory($runRoot)
$props=@('-p:ImportDirectoryBuildProps=false','-p:ImportDirectoryBuildTargets=false','-p:ImportDirectoryPackagesProps=false','-p:ImportDirectorySolutionProps=false','-p:ImportDirectorySolutionTargets=false',"-p:CustomBeforeMicrosoftCommonProps=$(Join-Path $buildRoot 'V4.Build.props')")
Push-Location $buildRoot;try{& dotnet restore $project --configfile (Join-Path $buildRoot 'NuGet.config') --artifacts-path (Join-Path $runRoot 'build') -nologo @props;if($LASTEXITCODE){throw 'P8 restore failed'};& dotnet build $project --no-restore --configuration Release --artifacts-path (Join-Path $runRoot 'build') -nologo @props;if($LASTEXITCODE){throw 'P8 build failed'}}finally{Pop-Location}
$target=Join-Path $runRoot 'target';$state=Join-Path $runRoot 'state';$evidence=Join-Path $runRoot 'evidence';foreach($path in @($target,$state,$evidence)){[void][IO.Directory]::CreateDirectory($path)}
Write-Utf8(Join-Path $target 'input.txt')"synthetic-ok`n";Write-Utf8(Join-Path $target 'Contracts/Synthetic.Contracts.csproj')'<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><AssemblyName>Synthetic.Contracts</AssemblyName></PropertyGroup></Project>';Write-Utf8(Join-Path $target 'Contracts/Contracts.cs')'namespace Synthetic.Contracts { public interface IPort { } } namespace Synthetic.ForbiddenTypes { public sealed class ForbiddenType { } } namespace Synthetic.ForbiddenApi { public static class Calls { public static void Use() { } } } namespace Synthetic.ForbiddenPayload { public sealed class Payload { } } namespace Synthetic.ForbiddenImport { public sealed class Marker { } }';Write-Utf8(Join-Path $target 'Application/Synthetic.Application.csproj')'<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><AssemblyName>Synthetic.Application</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../Contracts/Synthetic.Contracts.csproj" /></ItemGroup></Project>';Write-Utf8(Join-Path $target 'Application/Application.cs')'namespace Synthetic.Application.Allowed { public sealed class Port : Synthetic.Contracts.IPort { } }'
$packageBefore=Tree-Hash $packageRoot;$targetBefore=Tree-Hash $target;$projectId=$null
foreach($stage in @('bootstrap','analysis','pre','post')){$run=Host @('stage','run','--stage',$stage,'--package-root',$packageRoot,'--target-root',$target,'--state-root',$state,'--evidence-root',$evidence,'--profile','synthetic_profile');if($run.Code-ne0){$failures.Add("$stage failed: $($run.Text)");continue};$result=$run.Text|ConvertFrom-Json;if($result.status-cne'pass'-or$result.executedStages.Count-ne1-or$result.executedStages[0]-cne$stage){$failures.Add("$stage result identity invalid")};if(-not$projectId){$projectId=(Get-Content -Raw (Join-Path $state 'state.json')|ConvertFrom-Json).projectInstances[0].id}}
$preview=Host @('reset','factory','--mode','preview','--package-root',$packageRoot,'--state-root',$state,'--evidence-root',$evidence);if($preview.Code-ne0){$failures.Add("factory preview failed: $($preview.Text)")}else{$manifest=$preview.Text|ConvertFrom-Json;$apply=Host @('reset','factory','--mode','apply','--package-root',$packageRoot,'--state-root',$state,'--evidence-root',$evidence,'--accept-manifest-hash',[string]$manifest.manifestHash);if($apply.Code-ne0){$failures.Add("factory apply failed: $($apply.Text)")}}
if(@(Get-ChildItem (Join-Path $state 'projects') -Force -ErrorAction SilentlyContinue).Count-ne0-or@(Get-ChildItem (Join-Path $evidence 'projects') -Force -ErrorAction SilentlyContinue).Count-ne0){$failures.Add('factory reset left project mutable data')};if((Tree-Hash $packageRoot)-cne$packageBefore){$failures.Add('acceptance changed PackageRoot')};if((Tree-Hash $target)-cne$targetBefore){$failures.Add('acceptance changed TargetRoot')}
if($failures.Count){throw($failures-join"`n")};Write-Host 'V4 P8 V1 acceptance passed: clean Bootstrap/Analysis/Pre/Post, composite architecture and accepted factory reset with immutable package/target.'
