<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NoFlow.Carrier\NoFlow.Carrier.csproj" />
  </ItemGroup>

</Project>
