<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Platform\Messaging\IFX.Platform.Messaging.Abstractions\IFX.Platform.Messaging.Abstractions.csproj" />
  </ItemGroup>

</Project>
