<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IFX.Platform.Authorization.Contracts\IFX.Platform.Authorization.Contracts.csproj" />
    <ProjectReference Include="..\IFX.Platform.Authorization.Runtime\IFX.Platform.Authorization.Runtime.csproj" />
    <ProjectReference Include="..\IFX.Platform.Authorization.Infrastructure.Opa\IFX.Platform.Authorization.Infrastructure.Opa.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
