<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\App.Abstractions\App.Abstractions.csproj" />
    <ProjectReference Include="..\IFX.Modules.CRM.Application\IFX.Modules.CRM.Application.csproj" />
    <ProjectReference Include="..\IFX.Modules.CRM.Contracts\IFX.Modules.CRM.Contracts.csproj" />
    <ProjectReference Include="..\IFX.Modules.CRM.Infrastructure\IFX.Modules.CRM.Infrastructure.csproj" />
    <ProjectReference Include="..\IFX.Modules.CRM.Presentation\IFX.Modules.CRM.Presentation.csproj" />
  </ItemGroup>

</Project>
