// <auto-generated />
using System;
using IFX.Modules.CRM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IFX.Modules.CRM.Infrastructure.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.AdvisorInvestmentAccountLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdvisorPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("InvestmentAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RebateRate")
                        .IsRequired()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorPartyId");

                    b.HasIndex("InvestmentAccountId");

                    b.HasIndex("TenantId", "InvestmentAccountId", "AdvisorPartyId")
                        .HasDatabaseName("IX_AdvisorInvestmentAccountLinks_TenantId_AccountId_AdvisorPartyId");

                    b.ToTable("AdvisorInvestmentAccountLinks", "crm");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.CorporateInvestorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abn")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Acn")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("CountryOfIncorporation")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FrankieOneEntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("IncorporationDate")
                        .HasColumnType("date");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsPubliclyListed")
                        .HasColumnType("bit");

                    b.Property<string>("LicenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Regulator")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvestorId")
                        .IsUnique()
                        .HasDatabaseName("IX_CorporateInvestorProfiles_InvestorId");

                    b.ToTable("CorporateInvestorProfiles", "crm");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.IndividualInvestorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfDeath")
                        .HasColumnType("date");

                    b.Property<string>("FrankieOneEntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdDocumentCountry")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateOnly?>("IdDocumentExpiry")
                        .HasColumnType("date");

                    b.Property<string>("IdDocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdDocumentType")
                        .HasColumnType("int");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nationality")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvestorId")
                        .IsUnique()
                        .HasDatabaseName("IX_IndividualInvestorProfiles_InvestorId");

                    b.ToTable("IndividualInvestorProfiles", "crm");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.InvestmentAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CertificateDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_InvestmentAccounts_TenantId_AccountNumber");

                    b.ToTable("InvestmentAccounts", "crm");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.Investor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AmlCheckedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AmlGatewayReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AmlStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FatcaCrsStatus")
                        .HasColumnType("int");

                    b.Property<string>("GIIN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InvestorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsPEP")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("KycReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KycStatus")
                        .HasColumnType("int");

                    b.Property<int>("LegalStructure")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PepDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceOfWealth")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TIN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxResidencyCountry")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnresolvedAdverseMediaCount")
                        .HasColumnType("int");

                    b.Property<int>("UnresolvedPepCount")
                        .HasColumnType("int");

                    b.Property<int>("UnresolvedSanctionCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "InvestorCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Investors_TenantId_InvestorCode");

                    b.HasIndex("TenantId", "PartyId")
                        .IsUnique()
                        .HasDatabaseName("IX_Investors_TenantId_PartyId")
                        .HasFilter("[PartyId] IS NOT NULL");

                    b.ToTable("Investors", "crm");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.InvestorDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IssueCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("IssueState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvestorId");

                    b.HasIndex("TenantId", "InvestorId")
                        .HasDatabaseName("IX_InvestorDocuments_TenantId_InvestorId");

                    b.ToTable("InvestorDocuments", "crm");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LegalStructure")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PartyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PartyCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Parties_TenantId_PartyCode");

                    b.ToTable("Parties", "crm");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.PartyInvestmentAccountLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("InvestmentAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LinkOrder")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal?>("OwnershipPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentAccountId");

                    b.HasIndex("PartyId");

                    b.HasIndex("TenantId", "InvestmentAccountId", "PartyId")
                        .HasDatabaseName("IX_PartyInvestmentAccountLinks_TenantId_AccountId_PartyId");

                    b.ToTable("PartyInvestmentAccountLinks", "crm");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.PartyRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FromPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromPartyId");

                    b.HasIndex("ToPartyId");

                    b.HasIndex("TenantId", "FromPartyId", "RelationshipType")
                        .HasDatabaseName("IX_PartyRelationships_TenantId_FromPartyId_Type");

                    b.ToTable("PartyRelationships", "crm");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.PartyRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("TenantId", "PartyId", "Role")
                        .IsUnique()
                        .HasDatabaseName("IX_PartyRoleAssignments_TenantId_PartyId_Role");

                    b.ToTable("PartyRoleAssignments", "crm");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.TrustInvestorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FrankieOneEntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrustDeedReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("TrustEstablishedDate")
                        .HasColumnType("date");

                    b.Property<string>("TrustType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TrusteePartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvestorId")
                        .IsUnique()
                        .HasDatabaseName("IX_TrustInvestorProfiles_InvestorId");

                    b.ToTable("TrustInvestorProfiles", "crm");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.UserPartyLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("TenantId", "PartyId")
                        .HasDatabaseName("IX_UserPartyLinks_TenantId_PartyId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserPartyLinks_TenantId_UserId");

                    b.ToTable("UserPartyLinks", "crm");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.AdvisorInvestmentAccountLink", b =>
                {
                    b.HasOne("IFX.Modules.CRM.Domain.Entities.Party", "AdvisorParty")
                        .WithMany()
                        .HasForeignKey("AdvisorPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IFX.Modules.CRM.Domain.Entities.InvestmentAccount", "InvestmentAccount")
                        .WithMany("AdvisorLinks")
                        .HasForeignKey("InvestmentAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdvisorParty");

                    b.Navigation("InvestmentAccount");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.CorporateInvestorProfile", b =>
                {
                    b.HasOne("IFX.Modules.CRM.Domain.Entities.Investor", "Investor")
                        .WithOne("CorporateProfile")
                        .HasForeignKey("IFX.Modules.CRM.Domain.Entities.CorporateInvestorProfile", "InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.IndividualInvestorProfile", b =>
                {
                    b.HasOne("IFX.Modules.CRM.Domain.Entities.Investor", "Investor")
                        .WithOne("IndividualProfile")
                        .HasForeignKey("IFX.Modules.CRM.Domain.Entities.IndividualInvestorProfile", "InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.InvestorDocument", b =>
                {
                    b.HasOne("IFX.Modules.CRM.Domain.Entities.Investor", "Investor")
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.PartyInvestmentAccountLink", b =>
                {
                    b.HasOne("IFX.Modules.CRM.Domain.Entities.InvestmentAccount", "InvestmentAccount")
                        .WithMany("PartyLinks")
                        .HasForeignKey("InvestmentAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IFX.Modules.CRM.Domain.Entities.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestmentAccount");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.PartyRelationship", b =>
                {
                    b.HasOne("IFX.Modules.CRM.Domain.Entities.Party", "FromParty")
                        .WithMany()
                        .HasForeignKey("FromPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IFX.Modules.CRM.Domain.Entities.Party", "ToParty")
                        .WithMany()
                        .HasForeignKey("ToPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromParty");

                    b.Navigation("ToParty");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.PartyRoleAssignment", b =>
                {
                    b.HasOne("IFX.Modules.CRM.Domain.Entities.Party", "Party")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.TrustInvestorProfile", b =>
                {
                    b.HasOne("IFX.Modules.CRM.Domain.Entities.Investor", "Investor")
                        .WithOne("TrustProfile")
                        .HasForeignKey("IFX.Modules.CRM.Domain.Entities.TrustInvestorProfile", "InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.UserPartyLink", b =>
                {
                    b.HasOne("IFX.Modules.CRM.Domain.Entities.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.InvestmentAccount", b =>
                {
                    b.Navigation("AdvisorLinks");

                    b.Navigation("PartyLinks");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.Investor", b =>
                {
                    b.Navigation("CorporateProfile");

                    b.Navigation("IndividualProfile");

                    b.Navigation("TrustProfile");
                });

            modelBuilder.Entity("IFX.Modules.CRM.Domain.Entities.Party", b =>
                {
                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
