<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Indirect.AppCarrier\Indirect.AppCarrier.csproj" />
    <ProjectReference Include="..\Indirect.PresCarrier\Indirect.PresCarrier.csproj" />
    <ProjectReference Include="..\Indirect.InfraCarrier\Indirect.InfraCarrier.csproj" />
  </ItemGroup>

</Project>
