<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\IFX.BuildingBlocks.Composition\IFX.BuildingBlocks.Composition.csproj" />
    <ProjectReference Include="..\..\..\Platform\BackgroundJobs\IFX.Platform.BackgroundJobs.Composition\IFX.Platform.BackgroundJobs.Composition.csproj" />
    <ProjectReference Include="..\..\..\Platform\BackgroundJobs\IFX.Platform.BackgroundJobs.Contracts\IFX.Platform.BackgroundJobs.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Platform\Notifications\IFX.Platform.Notifications.Contracts\IFX.Platform.Notifications.Contracts.csproj" />
    <ProjectReference Include="..\IFX.Modules.IAM.Application\IFX.Modules.IAM.Application.csproj" />
    <ProjectReference Include="..\..\..\Platform\Authentication\IFX.Platform.Authentication.Composition\IFX.Platform.Authentication.Composition.csproj" />
    <ProjectReference Include="..\IFX.Modules.IAM.Infrastructure\IFX.Modules.IAM.Infrastructure.csproj" />
    <ProjectReference Include="..\IFX.Modules.IAM.Presentation\IFX.Modules.IAM.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup><ProjectReference Include="..\..\..\Platform\Authorization\IFX.Platform.Authorization.Composition\IFX.Platform.Authorization.Composition.csproj" /></ItemGroup>
</Project>
