<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Platform\Context\IFX.Platform.Context.Contracts\IFX.Platform.Context.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Platform\Messaging\IFX.Platform.Messaging.Contracts\IFX.Platform.Messaging.Contracts.csproj" />
  </ItemGroup>
</Project>
