// <auto-generated />
using System;
using IFX.Modules.Transaction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IFX.Modules.Transaction.Infrastructure.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20260908100947_Plan02ReliableOutbox")]
    partial class Plan02ReliableOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("transaction")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IFX.Modules.Transaction.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DealReference")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateOnly?>("ExpectedSettlementDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpectedTradeDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Orders_TenantId");

                    b.HasIndex("TenantId", "OrderReference")
                        .IsUnique()
                        .HasDatabaseName("IX_Orders_TenantId_OrderReference");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Orders_TenantId_Status");

                    b.ToTable("Orders", "transaction");
                });

            modelBuilder.Entity("IFX.Modules.Transaction.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("AUD");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvestmentAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegId")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<decimal?>("NAVPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("SettlementDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("TargetClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Units")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Transactions_OrderId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Transactions_TenantId");

                    b.HasIndex("TenantId", "InvestmentAccountId")
                        .HasDatabaseName("IX_Transactions_TenantId_InvestmentAccountId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Transactions_TenantId_Status");

                    b.ToTable("Transactions", "transaction");
                });

            modelBuilder.Entity("IFX.Modules.Transaction.Infrastructure.Messaging.TransactionOutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CausationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EnvelopeVersion")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("TraceState")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("EventId");

                    b.HasIndex("PartitionKey", "Sequence")
                        .IsUnique();

                    b.HasIndex("State", "NextAttemptAt", "LeaseUntil");

                    b.ToTable("OutboxMessages", "transaction");
                });

            modelBuilder.Entity("IFX.Modules.Transaction.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("IFX.Modules.Transaction.Domain.Entities.Order", null)
                        .WithMany("Legs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("IFX.Modules.Transaction.Domain.ValueObjects.ChargeDetail", "ChargeDetails", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal?>("Rate")
                                .HasPrecision(11, 10)
                                .HasColumnType("decimal(11,10)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("nvarchar(35)");

                            b1.HasKey("TransactionId", "Id");

                            b1.ToTable("Transactions", "transaction");

                            b1.ToJson("ChargeDetails");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsMany("IFX.Modules.Transaction.Domain.ValueObjects.CommissionDetail", "CommissionDetails", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<decimal?>("PercentageWaived")
                                .HasPrecision(11, 10)
                                .HasColumnType("decimal(11,10)");

                            b1.Property<decimal?>("Rate")
                                .HasPrecision(11, 10)
                                .HasColumnType("decimal(11,10)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("nvarchar(35)");

                            b1.HasKey("TransactionId", "Id");

                            b1.ToTable("Transactions", "transaction");

                            b1.ToJson("CommissionDetails");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("IFX.Modules.Transaction.Domain.ValueObjects.DealingPriceDetails", "DealingPriceDetails", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("decimal(18,8)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");

                            b1.Property<string>("PriceType")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("nvarchar(35)")
                                .HasColumnName("PriceType");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions", "transaction");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("IFX.Modules.Transaction.Domain.ValueObjects.ExternalFundIdentifier", "ExternalFundIdentifier", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Identifier")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("nvarchar(35)")
                                .HasColumnName("ExternalFundId");

                            b1.Property<string>("OtherType")
                                .HasMaxLength(35)
                                .HasColumnType("nvarchar(35)")
                                .HasColumnName("ExternalFundIdOtherType");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("ExternalFundIdType");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions", "transaction");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsMany("IFX.Modules.Transaction.Domain.ValueObjects.TaxDetail", "TaxDetails", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<bool?>("ExemptionIndicator")
                                .HasColumnType("bit");

                            b1.Property<string>("ExemptionReason")
                                .HasMaxLength(350)
                                .HasColumnType("nvarchar(350)");

                            b1.Property<decimal?>("Rate")
                                .HasPrecision(11, 10)
                                .HasColumnType("decimal(11,10)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("nvarchar(35)");

                            b1.HasKey("TransactionId", "Id");

                            b1.ToTable("Transactions", "transaction");

                            b1.ToJson("TaxDetails");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("ChargeDetails");

                    b.Navigation("CommissionDetails");

                    b.Navigation("DealingPriceDetails");

                    b.Navigation("ExternalFundIdentifier");

                    b.Navigation("TaxDetails");
                });

            modelBuilder.Entity("IFX.Modules.Transaction.Domain.Entities.Order", b =>
                {
                    b.Navigation("Legs");
                });
#pragma warning restore 612, 618
        }
    }
}
