[CmdletBinding()]
param([string]$TargetRoot,[string]$SolutionLockPath='artifacts/guards/p10-ifx-c5b/solution-runs/7e653152cd764804bf3e2b989fd97276/evidence-lock.json',[string]$EvidenceRoot='artifacts/guards/p10-ifx-c1-r2c/output-runs')
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Assert([bool]$Ok,[string]$Why){if(-not $Ok){throw $Why}}
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function TextHash([string]$Text){[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($Text))).ToLowerInvariant()}
function Rel([string]$Path){[IO.Path]::GetRelativePath($repo,$Path).Replace('\','/')}
function WriteJson([string]$Path,$Value){[void][IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($Path));[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 100).Replace("`r`n","`n")+"`n"),[Text.UTF8Encoding]::new($false))}
function TreeLines([string]$Root){
    $files=@(foreach($relative in @('src','tests','tools')){
        $folder=Join-Path $Root $relative;Assert ([IO.Directory]::Exists($folder)) "Missing source root: $relative"
        Get-ChildItem -LiteralPath $folder -File -Recurse -Force|Where-Object{$_.Extension -in '.cs','.csproj','.props','.targets' -and $_.FullName -notmatch '[\\/](bin|obj|node_modules|dist)[\\/]'}
    })
    $solution=Join-Path $Root 'IFX.sln';Assert ([IO.File]::Exists($solution)) 'IFX.sln missing.';$files+=Get-Item $solution
    return @($files|Sort-Object FullName|ForEach-Object{"$([IO.Path]::GetRelativePath($Root,$_.FullName).Replace('\','/'))|$(Hash $_.FullName)"})
}
function Classify([string]$Name,[string]$Content,[string]$Relative='',[string]$Sha=''){
    if($Name -match '^IFX\.[A-Za-z0-9.]+\.GlobalUsings\.g\.cs$'){$kind='global-usings'}
    elseif($Name -match '^IFX\.[A-Za-z0-9.]+\.AssemblyInfo\.cs$'){$kind='assembly-info'}
    elseif($Name -ceq '.NETCoreApp,Version=v8.0.AssemblyAttributes.cs'){$kind='target-framework'}
    elseif($Name -ceq 'IFX.ApiHost.MvcApplicationPartsAssemblyInfo.cs'){$kind='mvc-parts'}
    elseif($Name -ceq 'RegexGenerator.g.cs'){$kind='regex-generator'}
    else{throw "Unrecognized generated C# file: $Name"}
    Assert ($Content -match '<auto-?generated' -or $Content -match '<autogenerated') "Generated marker missing: $Name"
    if($kind -ceq 'regex-generator'){
        Assert ($expectedGenerators.ContainsKey($Relative) -and $expectedGenerators[$Relative] -ceq $Sha) "Unknown or changed RegexGenerator output: $Relative"
        Assert ($Content -match 'namespace System\.Text\.RegularExpressions\.Generated' -and $Content -notmatch 'namespace IFX\.Modules\.CRM\.Domain') "Unexpected RegexGenerator source scope: $Relative"
        return $kind
    }
    Assert ($Content -notmatch '\b(namespace|class|struct|interface|record|enum)\s+[A-Za-z_]' -and $Content -notmatch '\busing\s+(?:global::)?IFX\.' -and $Content -notmatch 'IFX\.Modules\.[A-Za-z0-9_.]+\.(?:Domain\.Entities|Contracts\.V1)') "Business syntax in generated C#: $Name"
    $statements=@($Content -split '\r?\n'|Where-Object{$_ -and $_ -notmatch '^\s*//' -and $_ -notmatch '^\s*$'})
    Assert ($statements.Count -gt 0) "Empty generated C#: $Name"
    foreach($line in $statements){
        $ok=switch($kind){
            'global-usings' {$line -match '^global using System(?:\.[A-Za-z0-9_.]+)?;$' -or ($Relative -ceq 'src/ApiHost/IFX.ApiHost/obj/Release/net8.0/IFX.ApiHost.GlobalUsings.g.cs' -and $line -match '^global using Microsoft\.(?:AspNetCore\.(?:Builder|Hosting|Http|Routing)|Extensions\.(?:Configuration|DependencyInjection|Hosting|Logging));$')}
            'assembly-info' {$line -match '^using System(?:\.Reflection)?;$' -or $line -match '^\[assembly: System\.Reflection\.Assembly(?:Company|Configuration|FileVersion|InformationalVersion|Product|Title|Version)Attribute\("[^"\r\n]*"\)\]$'}
            'target-framework' {$line -ceq 'using System;' -or $line -ceq 'using System.Reflection;' -or $line -ceq '[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute(".NETCoreApp,Version=v8.0", FrameworkDisplayName = ".NET 8.0")]'}
            'mvc-parts' {$line -ceq 'using System;' -or $line -ceq 'using System.Reflection;' -or $line -match '^\[assembly: Microsoft\.AspNetCore\.Mvc\.ApplicationParts\.ApplicationPartAttribute\("[A-Za-z0-9_.]+"\)\]$'}
        }
        Assert ([bool]$ok) "Unapproved generated statement ($kind): $line"
    }
    return $kind
}
$repo=if($TargetRoot){[IO.Path]::GetFullPath($TargetRoot)}else{[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../../..'))}
$sdk=(& dotnet --version).Trim();Assert ($LASTEXITCODE -eq 0 -and $sdk -ceq '10.0.303') 'Pinned SDK drift.'
$dirty=@(& git -C $repo status --porcelain --untracked-files=all -- src tests tools IFX.sln Directory.Build.props Directory.Packages.props)
Assert ($LASTEXITCODE -eq 0 -and -not $dirty) 'Controlled generated-input inventory requires clean tracked source.'
$commit=(& git -C $repo rev-parse HEAD).Trim().ToLowerInvariant();Assert ($LASTEXITCODE -eq 0 -and $commit -cmatch '^[a-f0-9]{40}$') 'Target commit unavailable.'
Assert ($SolutionLockPath -cmatch '^artifacts/guards/p10-ifx-c5b/solution-runs/[a-f0-9]{32}/evidence-lock\.json$') 'Uncontrolled C5b lock path.'
$solutionFull=Join-Path $repo $SolutionLockPath;Assert ([IO.File]::Exists($solutionFull)) 'C5b lock missing.'
$solution=Get-Content $solutionFull -Raw|ConvertFrom-Json -Depth 100 -DateKind String
$now=[DateTimeOffset]::UtcNow
Assert ($solution.gate -ceq 'Solution' -and $solution.producer -ceq 'ifx-c5b-controlled-v1' -and $solution.result -ceq 'passed' -and $solution.projectCount -eq 81 -and $solution.totalTests -gt 0) 'C5b lock incomplete.'
Assert ([DateTimeOffset]::Parse([string]$solution.completedAt) -gt $now.AddHours(-24)) 'C5b lock stale.'
$tree=@(TreeLines $repo);$treeHash=TextHash ($tree -join "`n")
Assert ($tree.Count -eq $solution.sourceFileCount -and $treeHash -ceq $solution.sourceTreeSha256) 'Source differs from C5b lock.'
$v3Scanner=Join-Path $repo 'docs/guards/V3/stages/post/gates/architecture/dotnet/Guards.ArchitectureConformance/SourceFiles.cs'
$c1hScanner=Join-Path $repo 'docs/guards/candidates/ifx-gate-coverage-c1h/modules/ifx-source-policy/adapter.ps1'
Assert ((Hash $v3Scanner) -ceq '58e657e7340a58bde2c24efd6f41fa4605eeb09a2d1ab28a1d4847ac739081e2' -and (Hash $c1hScanner) -ceq 'a7123eb5a98e0865f7513fa631e066f7a14d6567b41de9b5c80a08454d07a253') 'Frozen generated-source exclusion implementation drift.'
Assert (([IO.File]::ReadAllText($v3Scanner) -match 'part is "obj" or "bin"') -and ([IO.File]::ReadAllText($c1hScanner) -match '\(guard\|guards\|bin\|obj\)')) 'Source exclusion semantics drift.'
$expectedGenerators=@{
    'src/BuildingBlocks/IFX.BuildingBlocks.Application/obj/Release/net8.0/generated/System.Text.RegularExpressions.Generator/System.Text.RegularExpressions.Generator.RegexGenerator/RegexGenerator.g.cs'='eb8ea2d24859e7e532e26553a294ca64f9865fdcb291328d9775e9d4399055f3'
    'src/BuildingBlocks/IFX.BuildingBlocks.EntityFrameworkCore/obj/Release/net8.0/generated/System.Text.RegularExpressions.Generator/System.Text.RegularExpressions.Generator.RegexGenerator/RegexGenerator.g.cs'='ee9acbaa90467ae37b19b947fe59245a8df4a0e6e9752392c1c677803bb35877'
    'src/Platform/Context/IFX.Platform.Context.Contracts/obj/Release/net8.0/generated/System.Text.RegularExpressions.Generator/System.Text.RegularExpressions.Generator.RegexGenerator/RegexGenerator.g.cs'='dcc96ab0ad9a361cd2153fb6ca0c338c91d98dd987c44a6c0b2ce42653897dbb'
    'src/Platform/Messaging/IFX.Platform.Messaging.Contracts/obj/Release/net8.0/generated/System.Text.RegularExpressions.Generator/System.Text.RegularExpressions.Generator.RegexGenerator/RegexGenerator.g.cs'='4466384ff98c6501d55423b596a2916f30dcb4737da48b1f257e4c41e5502fa1'
}
$projects=@(Get-ChildItem -LiteralPath (Join-Path $repo 'src') -Recurse -File -Filter '*.csproj'|Where-Object{$_.FullName -notmatch '[\\/](bin|obj)[\\/]'}|Sort-Object FullName)
Assert ($projects.Count -eq 58) 'C1 project set drift.'
$id=[guid]::NewGuid().ToString('N');$out=if([IO.Path]::IsPathFullyQualified($EvidenceRoot)){Join-Path $EvidenceRoot $id}else{Join-Path $repo "$EvidenceRoot/$id"}
[void][IO.Directory]::CreateDirectory($out)
$buildOut=@(& dotnet build (Join-Path $repo 'IFX.sln') -c Release --no-restore -t:Rebuild -p:EmitCompilerGeneratedFiles=true -v:q 2>&1)
[IO.File]::WriteAllText((Join-Path $out 'build-output.txt'),($buildOut -join "`n"),[Text.UTF8Encoding]::new($false))
Assert ($LASTEXITCODE -eq 0) "Controlled Rebuild failed; see $out/build-output.txt"
$approved=@{
    'Microsoft.AspNetCore.Analyzers.dll'='10c933218a78c0e209aa257bca2b9d19f58deaba233a335e22a80b34ff7561d8'
    'Microsoft.AspNetCore.Mvc.Analyzers.dll'='60d9de93ebd6ddd49855b0627c784f5304b1f10ae8f2a2abe0987aaeca8272bb'
    'Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll'='fe1378dbd99ca5a9e51ebe3f8be336793307b17e45d9250a1ec1f179ccc5b78d'
    'Microsoft.CodeAnalysis.NetAnalyzers.dll'='6a7eb7b737ae1b109efccc51d3874bf357a43d307819a2049966582a8e3bc87f'
}
$analyzers=[Collections.Generic.Dictionary[string,string]]::new([StringComparer]::OrdinalIgnoreCase);$analyzerItems=0
foreach($project in $projects){
    $lines=@(& dotnet msbuild $project.FullName -getItem:Analyzer -p:Configuration=Release -nologo 2>&1)
    Assert ($LASTEXITCODE -eq 0) "Analyzer evaluation failed: $(Rel $project.FullName)"
    try{$result=($lines -join "`n")|ConvertFrom-Json -Depth 30}catch{throw "Analyzer list is not JSON: $(Rel $project.FullName)"}
    foreach($item in @($result.Items.Analyzer|Where-Object{$_})){
        $analyzerItems++;$path=[IO.Path]::GetFullPath([string]$item.FullPath);$name=[IO.Path]::GetFileName($path)
        Assert ($approved.ContainsKey($name) -and $path -match '[\\/]sdk[\\/]10\.0\.303[\\/]Sdks[\\/]Microsoft\.NET\.Sdk(?:\.Web)?[\\/]analyzers[\\/]') "Unapproved analyzer: $path"
        $sha=Hash $path;Assert ($sha -ceq $approved[$name]) "Analyzer byte drift: $name"
        $analyzers[$path]=$sha
    }
}
Assert ($analyzers.Count -eq 4 -and $analyzerItems -eq 118) 'Analyzer subject count drift.'
$generated=@(Get-ChildItem -LiteralPath (Join-Path $repo 'src') -Recurse -File -Filter '*.cs'|Where-Object{$_.FullName -match '[\\/]obj[\\/]Release[\\/]net8\.0[\\/]'}|Sort-Object FullName)
Assert ($generated.Count -eq 179) "Generated C# inventory drift: $($generated.Count)"
$rows=[Collections.Generic.List[object]]::new();$kinds=@{}
foreach($file in $generated){
    $relative=Rel $file.FullName;$sha=Hash $file.FullName
    $kind=Classify $file.Name ([IO.File]::ReadAllText($file.FullName)) $relative $sha
    if(-not $kinds.ContainsKey($kind)){$kinds[$kind]=0};$kinds[$kind]++
    $rows.Add([ordered]@{path=$relative;sha256=$sha;kind=$kind})
}
Assert ($kinds['global-usings'] -eq 58 -and $kinds['assembly-info'] -eq 58 -and $kinds['target-framework'] -eq 58 -and $kinds['mvc-parts'] -eq 1 -and $kinds['regex-generator'] -eq 4) 'Generated output shape drift.'
$generatorOutputs=@($generated|Where-Object{$_.FullName -match '[\\/]generated[\\/]'});Assert ($generatorOutputs.Count -eq 4) 'Compiler source-generator output set drift.'
$negative=[Collections.Generic.List[object]]::new()
foreach($case in @(
    [ordered]@{id='unknown-generated-file';name='Business.g.cs';content='// <auto-generated/>`nnamespace IFX.Modules.CRM.Domain.Entities;' },
    [ordered]@{id='business-declaration-in-metadata';name='IFX.Modules.CRM.Domain.GlobalUsings.g.cs';content="// <auto-generated/>`nnamespace IFX.Modules.CRM.Domain.Entities;`nclass Injected {}"}
)){
    $blocked=$false;try{[void](Classify $case.name $case.content)}catch{$blocked=$true}
    Assert $blocked "Generated negative did not block: $($case.id)";$negative.Add([ordered]@{id=$case.id;status='blocked'})
}
Assert (-not $approved.ContainsKey('Custom.Generator.dll')) 'Custom analyzer negative did not block.';$negative.Add([ordered]@{id='custom-analyzer';status='blocked'})
$generatorPath=@($expectedGenerators.Keys|Sort-Object)[0]
$changed=$false;try{[void](Classify 'RegexGenerator.g.cs' "// <auto-generated/>`nnamespace System.Text.RegularExpressions.Generated {}" $generatorPath ('0'*64))}catch{$changed=$true}
Assert $changed 'Changed RegexGenerator output did not block.';$negative.Add([ordered]@{id='changed-regex-generator';status='blocked'})
$empty=@();Assert ($empty.Count -eq 0 -and $generated.Count -gt 0) 'Zero-subject control failed.';$negative.Add([ordered]@{id='zero-generated-subject';status='blocked'})
$now=[DateTimeOffset]::UtcNow
$lock=[ordered]@{formatVersion=1;gate='C1GeneratedInputDisposition';producer='ifx-c1-r2c-controlled-v1';result='passed';targetCommit=$commit;createdAt=$now.ToString('o');expiresAt=$now.AddHours(1).ToString('o');sdk=$sdk;configuration='Release';targetFramework='net8.0';sourceFileCount=$tree.Count;sourceTreeSha256=$treeHash;solutionLockPath=$SolutionLockPath;solutionLockSha256=Hash $solutionFull;projectCount=$projects.Count;analyzerItemCount=$analyzerItems;analyzers=@($analyzers.Keys|Sort-Object|ForEach-Object{[ordered]@{path=$_;sha256=$analyzers[$_]}});generatedFileCount=$generated.Count;generatorOutputCount=$generatorOutputs.Count;generatedFiles=@($rows.ToArray());kinds=$kinds;v3SourceFilesSha256=Hash $v3Scanner;c1hSourceAdapterSha256=Hash $c1hScanner;applicableGeneratedSyntaxSubjectCount=0;buildOutputSha256=Hash (Join-Path $out 'build-output.txt')}
$lockPath=Join-Path $out 'evidence-lock.json';WriteJson $lockPath $lock
WriteJson (Join-Path $out 'summary.json') ([ordered]@{formatVersion=1;status='pass';scope='r2c-bounded-generated-input-disposition';projectCount=58;analyzerItemCount=$analyzerItems;uniqueAnalyzers=$analyzers.Count;generatedFileCount=$generated.Count;generatorOutputCount=$generatorOutputs.Count;applicableGeneratedSyntaxSubjectCount=0;kinds=$kinds;negative=@($negative.ToArray());lockPath=Rel $lockPath;lockSha256=Hash $lockPath;notes=@('Four RegexGenerator files contain compiled types but are explicitly excluded from the frozen V3/C1h syntax scanner and lie outside the CRM Domain compiled type claim.','R3 must verify the exact output lock and invalidate it on drift; a successful build is not itself a C1 policy verdict.')})
Write-Output "IFX C1 R2c generated-input disposition passed: $out"
