<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuthSamples.Modules.Auth.Application\AuthSamples.Modules.Auth.Application.csproj" />
    <ProjectReference Include="..\AuthSamples.Modules.Auth.Infrastructure\AuthSamples.Modules.Auth.Infrastructure.csproj" />
    <ProjectReference Include="..\AuthSamples.Modules.Auth.Presentation\AuthSamples.Modules.Auth.Presentation.csproj" />
  </ItemGroup>

</Project>
