Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$claim='IFX.C5.HISTORY_INTEGRITY';$rule='HISTORY-INTEGRITY';$detector='ifx-history-integrity';$findings=[Collections.Generic.List[object]]::new();$matched=0
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Hash-Canonical([string]$Path){$text=[IO.File]::ReadAllText($Path).Replace("`r`n","`n").Replace("`r","`n");[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($text))).ToLowerInvariant()}
function Emit([string]$Status,[string]$Category,[string]$Message=''){$r=[ordered]@{formatVersion=1;status=$Status;exitCategory=$Category;findings=@($findings.ToArray());coverage=@([ordered]@{claimId=$claim;matched=[int]$matched;minimum=18})};if($Message){$r.message=$Message};[Console]::Out.WriteLine(($r|ConvertTo-Json -Depth 30 -Compress))}
function Stop-Adapter([string]$Category,[string]$Message){Emit 'error' $Category $Message;exit 0}
function Is-Under([string]$Path,[string]$Root){$r=[IO.Path]::GetRelativePath($Root,$Path);$r -ne '..' -and -not [IO.Path]::IsPathRooted($r) -and -not $r.StartsWith("..$([IO.Path]::DirectorySeparatorChar)",[StringComparison]::Ordinal)}
function Resolve-Target([string]$Relative){if([IO.Path]::IsPathRooted($Relative) -or $Relative -match '(^|[\\/])\.\.([\\/]|$)'){Stop-Adapter 'unsafe-path' "Unsafe history path: $Relative"};$full=[IO.Path]::GetFullPath((Join-Path $target $Relative));if(-not(Is-Under $full $target)){Stop-Adapter 'unsafe-path' "History path escapes TargetRoot: $Relative"};$cursor=$full;while(Is-Under $cursor $target){if([IO.File]::Exists($cursor) -or [IO.Directory]::Exists($cursor)){$item=Get-Item -LiteralPath $cursor -Force;if(($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0 -or $null -ne $item.LinkTarget){Stop-Adapter 'unsafe-path' "Linked history path: $Relative"}};if($cursor -ceq $target){break};$cursor=[IO.Path]::GetDirectoryName($cursor)};return $full}
function Record([string]$Subject,[string]$Kind,[bool]$Pass){$script:matched++;if(-not $Pass){$findings.Add([ordered]@{ruleId=$rule;subject=$Subject;evidenceKind=$Kind;detectorId=$detector;severity='blocking'})}}
if([string]::IsNullOrWhiteSpace($env:V4_STAGE_INPUT_JSON)){Stop-Adapter 'invalid-input' 'Stage input required.'}
try{$inputObject=$env:V4_STAGE_INPUT_JSON|ConvertFrom-Json -AsHashtable -Depth 100}catch{Stop-Adapter 'invalid-input' 'Malformed stage input.'}
if($inputObject.formatVersion -ne 1 -or $inputObject.stage -cne 'post' -or (@($inputObject.config.enabledClaims)-join '|') -cne $claim -or @($inputObject.relativeRoots) -notcontains 'docs' -or @($inputObject.relativeRoots) -notcontains 'mcp'){Stop-Adapter 'invalid-input' 'Stage or claim selection invalid.'}
if(-not [IO.Path]::IsPathFullyQualified([string]$inputObject.targetRoot)){Stop-Adapter 'invalid-input' 'TargetRoot must be absolute.'};$target=[IO.Path]::GetFullPath([string]$inputObject.targetRoot);if(-not [IO.Directory]::Exists($target)){Stop-Adapter 'prerequisite-missing' 'TargetRoot missing.'}
$policyFile=Join-Path $PSScriptRoot 'policy.json';if(-not [IO.File]::Exists($policyFile) -or (Hash $policyFile) -cne [string]$inputObject.config.policySha256){Stop-Adapter 'integrity-failure' 'History policy drift.'}
try{$policy=Get-Content $policyFile -Raw|ConvertFrom-Json -AsHashtable -Depth 100}catch{Stop-Adapter 'integrity-failure' 'Malformed history policy.'}
if($policy.formatVersion -ne 1 -or $policy.id -cne 'ifx-history-integrity-c5h' -or $policy.historicalOnly -ne $true -or $policy.sourceManifestSha256 -cne '6530806bdc71f9baa4a1ed7e4d4d26020aa9ceb328c55286c07a42f83ae99b20' -or @($policy.entries).Count -ne 15 -or @($policy.references).Count -ne 3){Stop-Adapter 'integrity-failure' 'History policy shape drift.'}
$unique=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
foreach($entry in $policy.entries){$relative=[string]$entry.path;if(-not $unique.Add($relative) -or [string]$entry.sha256 -cnotmatch '^[a-f0-9]{64}$'){Stop-Adapter 'integrity-failure' 'Duplicate or malformed history entry.'};$full=Resolve-Target $relative;$pass=$false;if([IO.File]::Exists($full)){try{$document=Get-Content $full -Raw|ConvertFrom-Json -AsHashtable -Depth 100;$actualFormat=if($document.Contains('formatVersion')){$document.formatVersion}else{$null};$actualResult=if($document.Contains('result')){$document.result}else{$null};$actualGate=if($document.Contains('gate')){$document.gate}else{$null};$actualPlan=if($document.Contains('plan')){$document.plan}else{$null};$pass=$null -ne $document -and $actualFormat -ceq $entry.formatVersion -and $actualResult -ceq $entry.summary.result -and $actualGate -ceq $entry.summary.gate -and $actualPlan -ceq $entry.summary.plan -and (Hash-Canonical $full) -cne '' -and (Hash-Canonical $full) -ceq $entry.sha256}catch{$pass=$false}};Record $relative 'historical-file' $pass}
foreach($reference in $policy.references){$source=[string]$reference.source;$destination=[string]$reference.target;$sourceFile=Resolve-Target $source;$targetFile=Resolve-Target $destination;Record "$source -> $destination" 'historical-reference' ([IO.File]::Exists($sourceFile) -and [IO.File]::Exists($targetFile))}
if($matched -ne 18){Stop-Adapter 'integrity-failure' 'History coverage drift.'}
if($findings.Count -gt 0){Emit 'fail' 'findings-blocking'}else{Emit 'pass' 'success'}
